/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import locadora.controller.FilmeController;
import locadora.model.Filme;

/**
 *
 * @author Usuario
 */
public class TelaConsultaFilme extends javax.swing.JFrame {
    private TelaCadastroItem telaCadastroItem;
    private TelaCadastroFilme telaCadastroFilme;
    /**
     * Creates new form TelaConsultaFilme
     */
    public TelaConsultaFilme() {
        initComponents();
    }
    
    public TelaConsultaFilme(TelaCadastroItem telaCadastroItem){
        this.telaCadastroItem = telaCadastroItem;
        initComponents();
    }
    
    public TelaConsultaFilme(TelaCadastroFilme telaCadastroFilme){
        this.telaCadastroFilme= telaCadastroFilme;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1TituloFilme = new javax.swing.JTextField();
        jButton1ConsultarFilme = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1ResultadoFilmes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vídeo Locadora ");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Titulo Filme:");

        jTextField1TituloFilme.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jButton1ConsultarFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        jButton1ConsultarFilme.setToolTipText("");
        jButton1ConsultarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarFilmeActionPerformed(evt);
            }
        });

        jTable1ResultadoFilmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Título", "Gênero", "Sinopse", "Duração"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1ResultadoFilmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1ResultadoFilmesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1ResultadoFilmes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1TituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1ConsultarFilme)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1TituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton1ConsultarFilme)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camera.png"))); // NOI18N
        jLabel1.setText("Consulta Filme");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ConsultarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarFilmeActionPerformed
        FilmeController fc = new FilmeController();
        DefaultTableModel tableModel = (DefaultTableModel) jTable1ResultadoFilmes.getModel();
        tableModel.setRowCount(0);
        
        try{
            ArrayList<Filme>filmes = fc.listarFilme(jTextField1TituloFilme.getText());
            filmes.forEach((Filme filme)->{
                tableModel.addRow(new Object[]{
                filme.getCodFilme(),
                filme.getTitulo(),
                filme.getGenero(),
                filme.getSinopse(),
                filme.getDuracao()  
                });
            });
            jTable1ResultadoFilmes.setModel(tableModel);
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Erro");
        }
    }//GEN-LAST:event_jButton1ConsultarFilmeActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        if(telaCadastroFilme!=null)
            telaCadastroFilme.setVisible(true);
        else
            telaCadastroItem.setVisible(true);
            
        
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jTable1ResultadoFilmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1ResultadoFilmesMouseClicked
        if(evt.getClickCount()==2){
            if(telaCadastroFilme!=null){
            Integer codFilme = (Integer) jTable1ResultadoFilmes.getModel().getValueAt(jTable1ResultadoFilmes.getSelectedRow(), 0);
            String  nome = (String) jTable1ResultadoFilmes.getModel().getValueAt(jTable1ResultadoFilmes.getSelectedRow(), 1);
            String  genero = (String) jTable1ResultadoFilmes.getModel().getValueAt(jTable1ResultadoFilmes.getSelectedRow(), 2);
            String  sinopse = (String) jTable1ResultadoFilmes.getModel().getValueAt(jTable1ResultadoFilmes.getSelectedRow(), 3);
            Integer  duracao = (Integer) jTable1ResultadoFilmes.getModel().getValueAt(jTable1ResultadoFilmes.getSelectedRow(), 4);
            telaCadastroFilme.buscarFilme(codFilme, nome, genero, sinopse, duracao);
            telaCadastroFilme.setVisible(true);
            this.dispose();
            }else{
                Integer codFilme = (Integer) jTable1ResultadoFilmes.getModel().getValueAt(jTable1ResultadoFilmes.getSelectedRow(), 0);
                String  nome = (String) jTable1ResultadoFilmes.getModel().getValueAt(jTable1ResultadoFilmes.getSelectedRow(), 1);
                telaCadastroItem.buscarFilme(codFilme,nome);
                telaCadastroItem.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_jTable1ResultadoFilmesMouseClicked

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ConsultarFilme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1ResultadoFilmes;
    private javax.swing.JTextField jTextField1TituloFilme;
    // End of variables declaration//GEN-END:variables
}
