/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import locadora.controller.ItemController;
import locadora.model.Item;

/**
 *
 * @author Usuario
 */
public class TelaConsultaItem extends javax.swing.JFrame  {
    TelaCadastroItem telaCadastroItem = null;
    TelaAlugarFilme telaAlugarFilme = null;
    TelaItemAlugado telaItemAlugado = null;
    TelaConfiguracaoSistema telaConfiguracaoSistema = null;
    Color bg =null;
    
    
    /**
     * Creates new form TelaConsultaItem
     */
    public TelaConsultaItem() {
        initComponents();
        telaConfiguracaoSistema = new TelaConfiguracaoSistema();
    }
    
    
    public TelaConsultaItem(TelaCadastroItem telaCadastroItem){
        initComponents();
        this.telaCadastroItem = telaCadastroItem;
        telaConfiguracaoSistema = new TelaConfiguracaoSistema();
    }
    
    public TelaConsultaItem(TelaAlugarFilme telaAlugarFilme){
        initComponents();
        this.telaAlugarFilme = telaAlugarFilme;
        telaConfiguracaoSistema = new TelaConfiguracaoSistema();
    }
    
    public TelaConsultaItem(TelaItemAlugado telaItemAlugado){
        initComponents();
        this.telaItemAlugado = telaItemAlugado;
        telaConfiguracaoSistema = new TelaConfiguracaoSistema();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1TituloFilme = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1BuscarFilme = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Informe o Título do Filme:");
        jLabel2.setToolTipText("");

        jTextField1TituloFilme.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Item", "Código Filme", "Título", "Tipo", "Preço", "Alugado(CodCliente)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1BuscarFilme.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1BuscarFilme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        jButton1BuscarFilme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1BuscarFilmeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1TituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jButton1BuscarFilme)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1BuscarFilme))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1TituloFilme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camera.png"))); // NOI18N
        jLabel1.setText("Consulta Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(341, 341, 341))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        if(telaCadastroItem!=null)
            telaCadastroItem.setVisible(true);
        else if(telaAlugarFilme!=null)
            telaAlugarFilme.setVisible(true);
        else
            telaItemAlugado.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1BuscarFilmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1BuscarFilmeActionPerformed
        ItemController ic = new ItemController();
        ArrayList<Item> itens = new ArrayList<>();
        try{
            itens = ic.consultaItem(jTextField1TituloFilme.getText());
            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
            tableModel.setRowCount(0);
            itens.forEach((Item item)->{
               tableModel.addRow(new Object[]{
                   item.getCodItem(),
                   item.getFilme().getCodFilme(),
                   item.getFilme().getTitulo(),
                   item.getTipo(),
                   item.getPreco(),
                   item.getCliente().getCodCliente()
               });
            });
            
            if(telaConfiguracaoSistema!=null){
                String cor = telaConfiguracaoSistema.getCorAlugado();
                if(cor.equals("Amarelo")){
                    bg = Color.YELLOW;
                }else if (cor.equals("Vermelho")){
                    bg = Color.RED;
                }else if(cor.equals("Azul")){
                    bg = Color.BLUE;
                }
            }
            
            jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if((Integer)table.getValueAt(row, 5)!=0)
                    label.setBackground(bg);
                else{
                    label.setBackground(Color.WHITE);
                    label.setForeground(Color.BLACK);
                }
                return label;
                }
            });
            jTable1.setModel(tableModel);
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1BuscarFilmeActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(evt.getClickCount()==2){
            Integer codItem = (Integer)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
            Integer codFilme = (Integer)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1);
            String titulo = (String)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2);
            String tipo = (String)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3);
            Double preco = (Double)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4);
            if(telaCadastroItem!=null){
            JOptionPane.showMessageDialog(rootPane, "Atualize os dados desse Item");
            telaCadastroItem.buscarItem(codFilme, codItem,titulo,tipo,preco);
            telaCadastroItem.setVisible(true);
            }else if(telaAlugarFilme!=null){
                telaAlugarFilme.buscarItem(codItem, titulo, tipo, preco);
                telaAlugarFilme.setVisible(true);
            }else{
                telaItemAlugado.buscarItem(titulo);
                telaItemAlugado.setVisible(true);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jTable1MouseClicked
   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1BuscarFilme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1TituloFilme;
    // End of variables declaration//GEN-END:variables

    
}
