/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

import java.io.FileInputStream;
import java.util.Properties;
import javax.swing.JOptionPane;
import locadora.controller.ConfigController;

/**
 *
 * @author Usuario
 */
public class TelaConfiguracaoSistema extends javax.swing.JFrame {

    /**
     * Creates new form TelaConfiguracaoSistema
     */
    public TelaConfiguracaoSistema() {
        initComponents();
        try{
        FileInputStream file = new FileInputStream("src\\locadora\\util\\configs.properties");
        Properties props = new Properties();
        props.load(file);  
        Boolean dataRetroativa = props.getProperty("prop.isdataretroativa").equals("Y")?true:false;
        Integer diasLocacao = Integer.parseInt(props.getProperty("prop.diaslocacao"));
        jSpinner1DiasLocacao.setValue(diasLocacao);
        jRadioButton1DataRetroativa.setSelected(dataRetroativa);
        for(int i=0;i<jComboBox1CorAtrasado.getItemCount();i++){
            if(jComboBox1CorAtrasado.getItemAt(i).equals(props.getProperty("prop.coratrasado")))
                jComboBox1CorAtrasado.setSelectedIndex(i);
        }
        for(int i=0;i<jComboBox2CorAlugado.getItemCount();i++){
            if(jComboBox2CorAlugado.getItemAt(i).equals(props.getProperty("prop.coralugado")))
                jComboBox2CorAlugado.setSelectedIndex(i);
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    public boolean getIsDataRetroativa(){
        return jRadioButton1DataRetroativa.isSelected();
    }
    
    public int getDiasLocacao(){
        return (Integer)jSpinner1DiasLocacao.getValue();
    }
    
    public String getCorAlugado(){
        return (String)jComboBox2CorAlugado.getSelectedItem();
    }
    
    public String getCorAtrasado(){
        return (String)jComboBox1CorAtrasado.getSelectedItem();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1SalvarConfig = new javax.swing.JButton();
        jSpinner1DiasLocacao = new javax.swing.JSpinner();
        jRadioButton1DataRetroativa = new javax.swing.JRadioButton();
        jComboBox1CorAtrasado = new javax.swing.JComboBox<>();
        jComboBox2CorAlugado = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dias Locação:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Retroativa(Alugar):");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Indicação Atrasado(COR):");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Indicação Alugado(COR):");

        jButton1SalvarConfig.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1SalvarConfig.setText("Salvar");
        jButton1SalvarConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalvarConfigActionPerformed(evt);
            }
        });

        jSpinner1DiasLocacao.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jSpinner1DiasLocacao.setModel(new javax.swing.SpinnerNumberModel(5, 1, 50, 1));
        jSpinner1DiasLocacao.setValue(5);

        jRadioButton1DataRetroativa.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jRadioButton1DataRetroativa.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1DataRetroativa.setText("Sim/Não");

        jComboBox1CorAtrasado.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox1CorAtrasado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vermelho", "Azul", "Amarelo" }));

        jComboBox2CorAlugado.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBox2CorAlugado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vermelho", "Azul", "Amarelo" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(38, 38, 38)
                                .addComponent(jSpinner1DiasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1CorAtrasado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox2CorAlugado, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton1DataRetroativa))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton1SalvarConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1DiasLocacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton1DataRetroativa)
                    .addComponent(jLabel2))
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1CorAtrasado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2CorAlugado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jButton1SalvarConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon.png"))); // NOI18N
        jLabel1.setText("Configurações do Sistema");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1)
                .addContainerGap(259, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_formWindowClosed

    private void jButton1SalvarConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalvarConfigActionPerformed
        ConfigController configController = new ConfigController();
        boolean sucesso = configController.salvarConfig((Integer)jSpinner1DiasLocacao.getValue(),jRadioButton1DataRetroativa.isSelected(),(String)jComboBox1CorAtrasado.getSelectedItem(),(String)jComboBox2CorAlugado.getSelectedItem());
        if(sucesso){
            JOptionPane.showMessageDialog(rootPane, "Configuração registrada com sucesso");
        }
    }//GEN-LAST:event_jButton1SalvarConfigActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1SalvarConfig;
    private javax.swing.JComboBox<String> jComboBox1CorAtrasado;
    private javax.swing.JComboBox<String> jComboBox2CorAlugado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1DataRetroativa;
    private javax.swing.JSpinner jSpinner1DiasLocacao;
    // End of variables declaration//GEN-END:variables
}
