/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import locadora.controller.ClienteController;
import locadora.model.Cliente;

/**
 *
 * @author Usuario
 */
public class TelaConsultaCliente extends javax.swing.JFrame {
    private TelaCadastroCliente telaCadastroCliente;
    private SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form TelaConsultaCliente
     */
    public TelaConsultaCliente() {
        initComponents();
    }
    
    public TelaConsultaCliente(TelaCadastroCliente telaCadastroCliente){
        this.telaCadastroCliente = telaCadastroCliente;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1NomeCliente = new javax.swing.JTextField();
        jButton1ConsultaCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1ResultadoCliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome Cliente:");

        jTextField1NomeCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jButton1ConsultaCliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1ConsultaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        jButton1ConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultaClienteActionPerformed(evt);
            }
        });

        jTable1ResultadoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF", "Email", "Endereço", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1ResultadoCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1ResultadoClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1ResultadoCliente);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1ConsultaCliente))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1NomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1ConsultaCliente)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/camera.png"))); // NOI18N
        jLabel1.setText("Consulta Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.dispose();
        telaCadastroCliente.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultaClienteActionPerformed
        ClienteController clienteController = new ClienteController();
        DefaultTableModel tableModel = (DefaultTableModel) jTable1ResultadoCliente.getModel();
        tableModel.setRowCount(0);
        ArrayList<Cliente> clientes = null;
        try{
            clientes = clienteController.consultaCliente(jTextField1NomeCliente.getText());
            if(clientes!=null){
                clientes.forEach((Cliente cliente)->{
                    tableModel.addRow(new Object[]{
                        cliente.getCodCliente(),
                        cliente.getNome(),
                        cliente.getCpf(),
                        cliente.getEmail(),
                        cliente.getEndereco(),
                        sdf.format(cliente.getdNascimento())
                    });
                });
                jTable1ResultadoCliente.setModel(tableModel);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ConsultaClienteActionPerformed

    private void jTable1ResultadoClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1ResultadoClienteMouseClicked
        if(evt.getClickCount()==2){
            Integer id = (Integer)jTable1ResultadoCliente.getModel().getValueAt(jTable1ResultadoCliente.getSelectedRow(), 0);
            String nome  = (String)jTable1ResultadoCliente.getModel().getValueAt(jTable1ResultadoCliente.getSelectedRow(), 1);
            String cpf  = (String)jTable1ResultadoCliente.getModel().getValueAt(jTable1ResultadoCliente.getSelectedRow(), 2);
            String email  = (String)jTable1ResultadoCliente.getModel().getValueAt(jTable1ResultadoCliente.getSelectedRow(), 3);
            String endereco  = (String)jTable1ResultadoCliente.getModel().getValueAt(jTable1ResultadoCliente.getSelectedRow(), 4);
            String dtNascimento  = (String)jTable1ResultadoCliente.getModel().getValueAt(jTable1ResultadoCliente.getSelectedRow(), 5);
            cpf = cpf.replace(".", "");
            dtNascimento = dtNascimento.replace("/", "");
            telaCadastroCliente.buscarCliente(id, nome, cpf, email, endereco, dtNascimento);
            telaCadastroCliente.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jTable1ResultadoClienteMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ConsultaCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1ResultadoCliente;
    private javax.swing.JTextField jTextField1NomeCliente;
    // End of variables declaration//GEN-END:variables
}
