/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import locadora.controller.CepController;
import locadora.controller.ClienteController;
import locadora.model.CEP;
import locadora.util.SistemaUtil;
import org.postgresql.shaded.com.ongres.scram.common.message.ClientFinalMessage;
/**
 *
 * @author Usuario
 */
public class TelaCadastroCliente extends javax.swing.JFrame implements SistemaUtil {
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private Integer codCliente = 0;
    /**
     * Creates new form TelaCadastroCliente
     */
    
    public void buscarCliente(Integer cod,String nome,String cpf,String email,String endereco,String dtNascimento){
        this.codCliente = cod;
        jTextField1Nome.setText(nome);
        jFormattedTextField2Cpf.setText(cpf);
        jTextField1Email.setText(email);
        jTextField2Endereco.setText(endereco);
        jFormattedTextField1DtNascimento.setText(dtNascimento);
        jLabel1.setText("Atualizar dados do Cliente");
        jButton1Limpar.setEnabled(false);
        jButton1Apagar.setEnabled(true);
        JOptionPane.showMessageDialog(rootPane, "Atualize os dados desse cliente");
    }
    
    public TelaCadastroCliente() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1Nome = new javax.swing.JTextField();
        jFormattedTextField1DtNascimento = new javax.swing.JFormattedTextField();
        jFormattedTextField2Cpf = new javax.swing.JFormattedTextField();
        jTextField2Endereco = new javax.swing.JTextField();
        jButton1Salvar = new javax.swing.JButton();
        jButton1Limpar = new javax.swing.JButton();
        jButton2Cancelar = new javax.swing.JButton();
        jButton3Consultar = new javax.swing.JButton();
        jLabel6Email = new javax.swing.JLabel();
        jTextField1Email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1Cep = new javax.swing.JTextField();
        jButton1Consultar = new javax.swing.JButton();
        jButton1Apagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon.png"))); // NOI18N
        jLabel1.setText("Cadastro de Clientes");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setToolTipText("");
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data de Nascimento:");

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Endereço:");

        jTextField1Nome.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        try {
            jFormattedTextField1DtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1DtNascimento.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        try {
            jFormattedTextField2Cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField2Cpf.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jTextField2Endereco.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jButton1Salvar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1Salvar.setText("Salvar");
        jButton1Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SalvarActionPerformed(evt);
            }
        });

        jButton1Limpar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1Limpar.setText("Limpar");
        jButton1Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1LimparActionPerformed(evt);
            }
        });

        jButton2Cancelar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton2Cancelar.setText("Cancelar");
        jButton2Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CancelarActionPerformed(evt);
            }
        });

        jButton3Consultar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton3Consultar.setText("Consultar");
        jButton3Consultar.setToolTipText("");
        jButton3Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ConsultarActionPerformed(evt);
            }
        });

        jLabel6Email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6Email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6Email.setText("E-mail:");

        jTextField1Email.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CEP:");

        jTextField1Cep.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextField1Cep.setToolTipText("");

        jButton1Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lupa.png"))); // NOI18N
        jButton1Consultar.setText("Consultar");
        jButton1Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ConsultarActionPerformed(evt);
            }
        });

        jButton1Apagar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton1Apagar.setText("Apagar");
        jButton1Apagar.setEnabled(false);
        jButton1Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ApagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6Email)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1Salvar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1Limpar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2Cancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3Consultar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1Apagar))
                    .addComponent(jTextField1Nome)
                    .addComponent(jTextField2Endereco, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField2Cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField1DtNascimento)
                    .addComponent(jTextField1Email)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1Consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField1DtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField2Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6Email)
                    .addComponent(jTextField1Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField1Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Salvar)
                    .addComponent(jButton1Limpar)
                    .addComponent(jButton2Cancelar)
                    .addComponent(jButton3Consultar)
                    .addComponent(jButton1Apagar))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SalvarActionPerformed
        String nome = jTextField1Nome.getText();
        String cpf = jFormattedTextField2Cpf.getText();
        String email = jTextField1Email.getText();
        String endereco = jTextField2Endereco.getText();
        boolean sucesso;
        try{
        Date birthDate = sdf.parse(jFormattedTextField1DtNascimento.getText());
        ClienteController clienteC = new ClienteController();
        if(codCliente==0){
            sucesso = clienteC.cadastraCliente(nome, cpf, email, endereco, birthDate);
            if(sucesso){
                JOptionPane.showMessageDialog(rootPane, "Cliente cadastrado com sucesso");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar cliente, verifique se informações estão corretas");
            }
        }else{
            sucesso = clienteC.atualizaCliente(codCliente, nome, cpf, email, endereco, birthDate);
            if(sucesso){
                JOptionPane.showMessageDialog(rootPane, "Cliente ATUALIZADO com sucesso");
            }else{
                JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar cliente, verifique se informações estão corretas");
            }
        }
        }catch(ParseException p){
            JOptionPane.showMessageDialog(rootPane, "Data informada inválida");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton1SalvarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        TelaPrincipal p = new TelaPrincipal();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void jButton1LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1LimparActionPerformed
        limpaTela();
    }//GEN-LAST:event_jButton1LimparActionPerformed

    private void jButton1ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ConsultarActionPerformed
        try{
        CEP cep = CepController.recebeCEP(jTextField1Cep.getText());
        if(cep!=null){
            jTextField2Endereco.setText("");
            jTextField2Endereco.setText("Rua:"+cep.getLogradouro()+" Bairro:"+cep.getBairro()+" Cidade:"+cep.getLocalidade()+" Nº:");
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Impossível consultar o cep no momento, digite manualmente");
        }
    }//GEN-LAST:event_jButton1ConsultarActionPerformed

    private void jButton3ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ConsultarActionPerformed
           TelaConsultaCliente telaConsultaCliente = new TelaConsultaCliente(this);
           telaConsultaCliente.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_jButton3ConsultarActionPerformed

    private void jButton2CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CancelarActionPerformed
        this.dispose();
       
    }//GEN-LAST:event_jButton2CancelarActionPerformed

    private void jButton1ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ApagarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja excluir esse registro?","Atenção", JOptionPane.OK_OPTION,JOptionPane.CANCEL_OPTION);
        if(resposta==0){
        ClienteController clienteC = new ClienteController();
        boolean sucesso;
        try{
            sucesso = clienteC.apagarCliente(codCliente);
            if(sucesso)
                JOptionPane.showMessageDialog(rootPane, "Cliente apagado com sucesso");
                
            else
                JOptionPane.showMessageDialog(rootPane, "Erro ao apagar cliente");
        }catch(Exception e){
            e.printStackTrace();
        }
        
        this.dispose();
        }
    }//GEN-LAST:event_jButton1ApagarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Apagar;
    private javax.swing.JButton jButton1Consultar;
    private javax.swing.JButton jButton1Limpar;
    private javax.swing.JButton jButton1Salvar;
    private javax.swing.JButton jButton2Cancelar;
    private javax.swing.JButton jButton3Consultar;
    private javax.swing.JFormattedTextField jFormattedTextField1DtNascimento;
    private javax.swing.JFormattedTextField jFormattedTextField2Cpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel6Email;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1Cep;
    private javax.swing.JTextField jTextField1Email;
    private javax.swing.JTextField jTextField1Nome;
    private javax.swing.JTextField jTextField2Endereco;
    // End of variables declaration//GEN-END:variables

    @Override
    public void limpaTela() {
        jTextField1Nome.setText("");
        jFormattedTextField1DtNascimento.setText("");
        jFormattedTextField2Cpf.setText("");
        jTextField1Email.setText("");
        jTextField2Endereco.setText("");
        jTextField1Cep.setText("");
        
    }
}
